// Minifies scripts/embed.src.js into lib/embedLoader.generated.ts, which the
// /embed.js route handler serves.
//
// The readable source deliberately lives outside public/ so it is never served,
// and the loader is served by a route rather than as a static file so the route
// can decide who gets it. Runs automatically before every build via "prebuild";
// run it by hand with `npm run build:embed` after editing the source.

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { minify } from 'terser'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const input = join(root, 'scripts', 'embed.src.js')
const output = join(root, 'lib', 'embedLoader.generated.ts')

const source = await readFile(input, 'utf8')

const result = await minify(source, {
  compress: { passes: 2, drop_console: true },
  mangle: true,
  format: { comments: false },
})

if (!result.code) {
  console.error('embed loader: minification produced no output')
  process.exit(1)
}

const file = `// Generated by scripts/build-embed.mjs from scripts/embed.src.js.
// Do not edit by hand — edit the source and run \`npm run build:embed\`.

export const EMBED_LOADER = ${JSON.stringify(result.code)}
`

await writeFile(output, file, 'utf8')

const saved = Math.round((1 - result.code.length / source.length) * 100)
console.log(`embed loader: ${source.length} -> ${result.code.length} bytes (${saved}% smaller)`)
